<?php

namespace Database\Seeders;

use App\Models\Recipe;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use RuntimeException;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // First, clear old recipes that might have broken images from previous runs
        Recipe::query()->delete();

        foreach ($this->recipes() as $recipeData) {
            $cook = $this->findCookOrFail($recipeData['cook_email']);

            $recipeData['prep_time_minutes'] = rand(15, 120);
            $recipeData['calories'] = rand(200, 900);
            $recipeData['rating'] = rand(35, 50) / 10;
            $recipeData['likes'] = rand(10, 1000);

            Recipe::updateOrCreate(
                [
                    'user_id' => $cook->id,
                    'title' => $recipeData['title'],
                ],
                Arr::except($recipeData, ['cook_email'])
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function recipes(): array
    {
        return [
            // ORIGINAL RECIPES
            [
                'cook_email' => 'moha@homeflavors.com',
                'title' => 'Moroccan Tagine',
                'description' => 'Traditional slow-cooked stew with aromatic spices and tender meat.',
                'ingredients' => 'lamb,spices,prunes,almonds,onions,ginger,cinnamon',
                'instructions' => "1. Brown the meat. 2. Add spices and slow cook. 3. Add prunes. 4. Serve.",
                'price' => 20.00,
                'image_url' => 'recipes/moroccan tajin.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Moroccan',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'nusret@homeflavors.com',
                'title' => 'Japanese Ramen',
                'description' => 'Rich, savory broth with fresh noodles and authentic toppings.',
                'ingredients' => 'ramen noodles,broth,chashu pork,soft-boiled egg,scallions,nori,bamboo shoots',
                'instructions' => "1. Make broth. 2. Boil noodles. 3. Assemble.",
                'price' => 18.00,
                'image_url' => 'recipes/Japanese Ramen.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Japanese',
                'city' => 'Tokyo',
                'country' => 'Japan',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'alain@homeflavors.com',
                'title' => 'Italian Pasta Carbonara',
                'description' => 'Creamy pasta with pancetta, eggs, and parmesan cheese.',
                'ingredients' => 'spaghetti,pancetta,eggs,parmesan,black pepper,guanciale',
                'instructions' => "1. Cook pasta. 2. Fry pancetta. 3. Mix eggs and cheese. 4. Combine.",
                'price' => 16.00,
                'image_url' => 'recipes/Italian Pasta Carbonara.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Italian',
                'city' => 'Rome',
                'country' => 'Italy',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'gordon@homeflavors.com',
                'title' => 'American Burger',
                'description' => 'Juicy beef patty with fresh vegetables and special sauce.',
                'ingredients' => 'beef patty,bun,lettuce,tomato,onion,pickles,cheese',
                'instructions' => "1. Grill patty. 2. Toast buns. 3. Assemble burger.",
                'price' => 14.00,
                'image_url' => 'recipes/American Burger.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'American',
                'city' => 'New York',
                'country' => 'USA',
                'continent' => 'NorthAmerica',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'ferran@homeflavors.com',
                'title' => 'Mexican Tacos',
                'description' => 'Soft corn tortillas filled with seasoned meat and fresh toppings.',
                'ingredients' => 'corn tortillas,ground beef,cilantro,onion,lime,salsa,cheese',
                'instructions' => "1. Cook beef. 2. Warm tortillas. 3. Assemble tacos.",
                'price' => 12.00,
                'image_url' => 'recipes/Mexican Tacos.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Mexican',
                'city' => 'Mexico City',
                'country' => 'Mexico',
                'continent' => 'NorthAmerica',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'gordon@homeflavors.com',
                'title' => 'Indian Butter Chicken',
                'description' => 'Rich, creamy curry with tender chicken pieces in tomato-based sauce.',
                'ingredients' => 'chicken,tomatoes,cream,butter,garam masala,garlic,ginger',
                'instructions' => "1. Marinate chicken. 2. Cook chicken. 3. Make sauce. 4. Combine.",
                'price' => 22.00,
                'image_url' => 'recipes/Indian Butter Chicken.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Indian',
                'city' => 'Delhi',
                'country' => 'India',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'alain@homeflavors.com',
                'title' => 'French Ratatouille',
                'description' => 'Traditional Provençal vegetable stew with eggplant, zucchini, and tomatoes.',
                'ingredients' => 'eggplant,zucchini,tomatoes,bell peppers,onions,herbs,olive oil',
                'instructions' => "1. Slice vegetables. 2. Sauté. 3. Simmer. 4. Serve.",
                'price' => 18.00,
                'image_url' => 'recipes/French Ratatouille.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'French',
                'city' => 'Nice',
                'country' => 'France',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'gordon@homeflavors.com',
                'title' => 'Chinese Dumplings',
                'description' => 'Delicate dumplings filled with pork and vegetables, served with dipping sauce.',
                'ingredients' => 'dumpling wrappers,pork,cabbage,scallions,ginger,soy sauce,sesame oil',
                'instructions' => "1. Make filling. 2. Wrap dumplings. 3. Steam or boil.",
                'price' => 15.00,
                'image_url' => 'recipes/Chinese Dumplings.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Chinese',
                'city' => 'Beijing',
                'country' => 'China',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'gordon@homeflavors.com',
                'title' => 'Pad Thai',
                'description' => 'Popular Thai stir-fried rice noodle dish with eggs, peanuts, and vegetables.',
                'ingredients' => 'rice noodles,eggs,peanuts,bean sprouts,tofu,lime,tamarind sauce',
                'instructions' => "1. Soak noodles. 2. Stir fry eggs and tofu. 3. Add noodles and sauce.",
                'price' => 16.00,
                'image_url' => 'recipes/Pad Thai.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Thai',
                'city' => 'Bangkok',
                'country' => 'Thailand',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'ferran@homeflavors.com',
                'title' => 'Moussaka',
                'description' => 'Classic Mediterranean casserole layered with eggplant, meat, and béchamel sauce.',
                'ingredients' => 'eggplant,minced meat,tomato sauce,béchamel sauce,cheese',
                'instructions' => "1. Layer eggplant and meat. 2. Top with béchamel. 3. Bake.",
                'price' => 20.00,
                'image_url' => 'recipes/Moussaka.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Greek',
                'city' => 'Athens',
                'country' => 'Greece',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'choumicha@homeflavors.com',
                'title' => 'Jollof Rice',
                'description' => 'Popular West African rice dish cooked with tomatoes, peppers, and spices.',
                'ingredients' => 'rice,tomatoes,onions,peppers,spices,chicken,vegetables',
                'instructions' => "1. Blend tomatoes. 2. Cook sauce. 3. Add rice and simmer.",
                'price' => 18.00,
                'image_url' => 'recipes/Jollof Rice.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Nigerian',
                'city' => 'Lagos',
                'country' => 'Nigeria',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'ferran@homeflavors.com',
                'title' => 'Brazilian Feijoada',
                'description' => 'Traditional Brazilian black bean stew cooked with a variety of salted and smoked meats.',
                'ingredients' => 'black beans,pork ribs,smoked sausage,beef,garlic,onion,bay leaves,rice,orange slices',
                'instructions' => "1. Cook beans. 2. Add meats. 3. Simmer. 4. Serve with rice.",
                'price' => 24.00,
                'image_url' => 'recipes/Brazillian feijoada.jpeg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Brazilian',
                'city' => 'Rio de Janeiro',
                'country' => 'Brazil',
                'continent' => 'SouthAmerica',
                'status' => 'approved',
            ],
            // CHEF RECIPES
            [
                'cook_email' => 'ferran@homeflavors.com',
                'title' => 'Spanish Paella',
                'description' => 'Traditional saffron-infused rice dish with seafood and vegetables.',
                'ingredients' => 'rice,saffron,seafood,vegetables,olive oil,onions,peppers',
                'instructions' => "1. Heat oil in a paella pan.\n2. Sauté onions and peppers.\n3. Add rice and saffron broth.\n4. Arrange seafood on top.\n5. Simmer until rice is tender.",
                'price' => 25.00,
                'image_url' => 'recipes/Spanish Paella.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Spanish',
                'city' => 'Valencia',
                'country' => 'Spain',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'ferran@homeflavors.com',
                'title' => 'Gazpacho',
                'description' => 'Refreshing cold soup made with ripe tomatoes and vegetables.',
                'ingredients' => 'tomatoes,cucumber,pepper,onions,vinegar,olive oil',
                'instructions' => "1. Chop all vegetables.\n2. Blend until smooth.\n3. Season with salt, vinegar, and olive oil.\n4. Chill for at least 2 hours.\n5. Serve cold.",
                'price' => 12.00,
                'image_url' => 'recipes/Gazpacho.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Spanish',
                'city' => 'Andalusia',
                'country' => 'Spain',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'ferran@homeflavors.com',
                'title' => 'Tapas Platter',
                'description' => 'Assortment of small Spanish dishes perfect for sharing.',
                'ingredients' => 'chorizo,manchego cheese,jamón,olives,patatas bravas,croquettes',
                'instructions' => "1. Prepare patatas bravas.\n2. Fry croquettes.\n3. Arrange meats and cheeses on a board.\n4. Add olives and bread.\n5. Serve immediately.",
                'price' => 35.00,
                'image_url' => 'recipes/Tapas Platter.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Spanish',
                'city' => 'Madrid',
                'country' => 'Spain',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'choumicha@homeflavors.com',
                'title' => 'Koshari',
                'description' => 'Egyptian comfort food combining rice, lentils, and pasta topped with spicy tomato sauce.',
                'ingredients' => 'rice,lentils,pasta,chickpeas,tomato sauce,garlic,fried onions',
                'instructions' => "1. Cook rice, lentils, and pasta separately.\n2. Prepare spicy tomato sauce.\n3. Fry onions until crispy.\n4. Layer rice, lentils, and pasta.\n5. Top with sauce and onions.",
                'price' => 15.00,
                'image_url' => 'recipes/Koshari.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Egyptian',
                'city' => 'Cairo',
                'country' => 'Egypt',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'choumicha@homeflavors.com',
                'title' => 'Ful Medames',
                'description' => 'Traditional Egyptian fava bean stew seasoned with herbs and spices.',
                'ingredients' => 'fava beans,lemon juice,olive oil,garlic,cumin,parsley',
                'instructions' => "1. Soak beans overnight.\n2. Simmer until tender.\n3. Mash slightly with garlic and cumin.\n4. Drizzle with olive oil and lemon juice.\n5. Garnish with parsley.",
                'price' => 10.00,
                'image_url' => 'recipes/Ful Medames.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Egyptian',
                'city' => 'Alexandria',
                'country' => 'Egypt',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'choumicha@homeflavors.com',
                'title' => 'Molokhia',
                'description' => 'Nutritious Egyptian soup made with jute leaves and chicken.',
                'ingredients' => 'molokhia leaves,chicken,coriander,garlic,chili,rice',
                'instructions' => "1. Cook chicken to make broth.\n2. Mince molokhia leaves.\n3. Add leaves to broth.\n4. Sauté garlic and coriander, then stir in.\n5. Serve over rice.",
                'price' => 18.00,
                'image_url' => 'recipes/Molokhia.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Egyptian',
                'city' => 'Cairo',
                'country' => 'Egypt',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'gordon@homeflavors.com',
                'title' => 'Pho',
                'description' => 'Vietnamese noodle soup with aromatic herbs and tender beef.',
                'ingredients' => 'rice noodles,beef broth,beef,herbs,lime,bean sprouts,onions',
                'instructions' => "1. Simmer beef bones for hours to make broth.\n2. Cook rice noodles.\n3. Place noodles and raw beef slices in a bowl.\n4. Pour boiling broth over meat to cook.\n5. Garnish with herbs and sprouts.",
                'price' => 14.00,
                'image_url' => 'recipes/Pho.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Vietnamese',
                'city' => 'Hanoi',
                'country' => 'Vietnam',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'gordon@homeflavors.com',
                'title' => 'Banh Mi',
                'description' => 'Vietnamese sandwich with pickled vegetables and grilled meat.',
                'ingredients' => 'baguette,pate,pickled vegetables,cilantro,jalapeños,meat',
                'instructions' => "1. Slice and toast the baguette.\n2. Spread pate on the bread.\n3. Add grilled meat.\n4. Top with pickled carrots, daikon, and cilantro.\n5. Add jalapeños for spice.",
                'price' => 9.00,
                'image_url' => 'recipes/Banh Mi.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Vietnamese',
                'city' => 'Ho Chi Minh',
                'country' => 'Vietnam',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'gordon@homeflavors.com',
                'title' => 'Spring Rolls',
                'description' => 'Fresh Vietnamese rolls filled with vegetables and shrimp.',
                'ingredients' => 'rice paper,shrimp,vermicelli,lettuce,mint,carrots,peanuts',
                'instructions' => "1. Soften rice paper in water.\n2. Layer lettuce, vermicelli, and shrimp.\n3. Add mint and carrots.\n4. Roll tightly.\n5. Serve with peanut dipping sauce.",
                'price' => 11.00,
                'image_url' => 'recipes/Spring Rolls.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Vietnamese',
                'city' => 'Hoi An',
                'country' => 'Vietnam',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'alain@homeflavors.com',
                'title' => 'Risotto alla Milanese',
                'description' => 'Creamy Italian rice dish flavored with saffron.',
                'ingredients' => 'arborio rice,saffron,white wine,onions,parmesan,butter',
                'instructions' => "1. Sauté onions in butter.\n2. Toast the rice.\n3. Deglaze with white wine.\n4. Gradually add warm broth and saffron.\n5. Stir in parmesan and butter to finish.",
                'price' => 22.00,
                'image_url' => 'recipes/Risotto alla Milanese.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Italian',
                'city' => 'Milan',
                'country' => 'Italy',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'alain@homeflavors.com',
                'title' => 'Osso Buco',
                'description' => 'Braised veal shanks with vegetables, white wine and broth.',
                'ingredients' => 'veal shanks,white wine,onions,carrots,celery,broth,gremolata',
                'instructions' => "1. Brown the veal shanks.\n2. Sauté mirepoix.\n3. Return meat, add wine and broth.\n4. Braise slowly until tender.\n5. Garnish with fresh gremolata.",
                'price' => 34.00,
                'image_url' => 'recipes/Osso Buco.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Italian',
                'city' => 'Milan',
                'country' => 'Italy',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'alain@homeflavors.com',
                'title' => 'Tiramisu',
                'description' => 'Classic Italian dessert with coffee-soaked ladyfingers and mascarpone cream.',
                'ingredients' => 'ladyfingers,mascarpone,coffee,eggs,sugar,cocoa powder',
                'instructions' => "1. Whisk egg yolks and sugar, then mix in mascarpone.\n2. Beat egg whites and fold in.\n3. Dip ladyfingers in espresso.\n4. Layer cookies and cream.\n5. Dust with cocoa and chill.",
                'price' => 12.00,
                'image_url' => 'recipes/Tiramisu.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Italian',
                'city' => 'Venice',
                'country' => 'Italy',
                'continent' => 'Europe',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'moha@homeflavors.com',
                'title' => 'Tagine of Lamb',
                'description' => 'Slow-cooked Moroccan stew with aromatic spices and tender lamb.',
                'ingredients' => 'lamb,apricots,almonds,onions,ginger,cinnamon,saffron',
                'instructions' => "1. Brown the lamb with spices.\n2. Add onions and broth.\n3. Simmer in a tagine.\n4. Add apricots towards the end.\n5. Garnish with toasted almonds.",
                'price' => 28.00,
                'image_url' => 'recipes/Tagine of Lamb.jpg.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Moroccan',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'moha@homeflavors.com',
                'title' => 'Couscous',
                'description' => 'Moroccan steamed semolina with vegetables and meat.',
                'ingredients' => 'couscous,chicken,lamb,carrots,zucchini,raisins,harissa',
                'instructions' => "1. Steam couscous over the broth.\n2. Cook meat with spices.\n3. Add vegetables based on cooking time.\n4. Fluff couscous with butter.\n5. Serve with meat and vegetables on top.",
                'price' => 24.00,
                'image_url' => 'recipes/Couscous.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Moroccan',
                'city' => 'Casablanca',
                'country' => 'Morocco',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'moha@homeflavors.com',
                'title' => 'Harira',
                'description' => 'Traditional Moroccan soup made with tomatoes, lentils, and chickpeas.',
                'ingredients' => 'tomatoes,lentils,chickpeas,onions,celery,cilantro,turmeric',
                'instructions' => "1. Sauté onions and celery.\n2. Add tomatoes, lentils, chickpeas, and spices.\n3. Simmer until tender.\n4. Thicken with flour mixture if desired.\n5. Stir in fresh cilantro before serving.",
                'price' => 10.00,
                'image_url' => 'recipes/Harira.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Moroccan',
                'city' => 'Fez',
                'country' => 'Morocco',
                'continent' => 'Africa',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'nusret@homeflavors.com',
                'title' => 'Ramen',
                'description' => 'Rich, savory Japanese noodle soup with various toppings.',
                'ingredients' => 'ramen noodles,broth,chashu pork,soft-boiled egg,scallions,nori,bamboo shoots',
                'instructions' => "1. Prepare complex broth over two days.\n2. Cook noodles until al dente.\n3. Slice chashu pork.\n4. Assemble bowl with broth, noodles, and toppings.\n5. Serve immediately.",
                'price' => 16.00,
                'image_url' => 'recipes/Japanese Ramen.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Japanese',
                'city' => 'Tokyo',
                'country' => 'Japan',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'nusret@homeflavors.com',
                'title' => 'Tempura',
                'description' => 'Lightly battered and fried Japanese seafood and vegetables.',
                'ingredients' => 'shrimp,vegetables,tempura flour,ice water,dipping sauce,grated daikon',
                'instructions' => "1. Prepare ice-cold batter.\n2. Dip shrimp and vegetables.\n3. Fry briefly in hot oil until crispy.\n4. Drain on wire rack.\n5. Serve with warm dipping sauce.",
                'price' => 18.00,
                'image_url' => 'recipes/tempura.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Japanese',
                'city' => 'Osaka',
                'country' => 'Japan',
                'continent' => 'Asia',
                'status' => 'approved',
            ],
            [
                'cook_email' => 'nusret@homeflavors.com',
                'title' => 'Onigiri',
                'description' => 'Japanese rice balls with various fillings wrapped in seaweed.',
                'ingredients' => 'short-grain rice,seaweed,fillings,salt,seasoning',
                'instructions' => "1. Cook and cool the rice.\n2. Wet hands and rub with salt.\n3. Form rice into a triangle around the filling.\n4. Wrap with a strip of nori.\n5. Serve as a snack or light meal.",
                'price' => 6.00,
                'image_url' => 'recipes/Onigiri.jpg',
                'youtube_url' => 'https://www.youtube.com/embed/1234567890',
                'category' => 'Japanese',
                'city' => 'Kyoto',
                'country' => 'Japan',
                'continent' => 'Asia',
                'status' => 'approved',
            ]
        ];
    }

    private function findCookOrFail(string $email): User
    {
        $cook = User::query()
            ->where('email', $email)
            ->where('role', 'cook')
            ->first();

        if (! $cook) {
            throw new RuntimeException("Unable to seed recipes because cook [{$email}] was not found.");
        }

        return $cook;
    }
}
